export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_NOTALLOWED = 'AUTH_NOTALLOWED';

export const SESSION_SAVE = 'SESSION_SAVE';
export const SESSION_CLEAR = 'SESSION_CLEAR';