export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESSFULL = 'REGISTRATION_SUCCESSFULL';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESSFULL = 'AUTH_SUCCESSFULL';
export const AUTH_FAIL = 'REGISTRATION_FAIL';



export const SESSION_SAVE = 'SESSION_SAVE';
export const SESSION_CLEAR = 'SESSION_CLEAR';