export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_NOTALLOWED = 'AUTH_NOTALLOWED';

export const SESSION_SAVE = 'SESSION_SAVE';
export const SESSION_CLEAR = 'SESSION_CLEAR';


export const ADVERTS_REQUEST = 'ADVERTS_REQUEST';
export const ADVERTS_SUCCESSFUL = 'ADVERTS_SUCCESSFUL';
export const ADVERTS_FAIL = 'ADVERTS_FAIL';

export const ADVERT_REQUEST = 'ADVERT_REQUEST';
export const ADVERT_SUCCESSFUL = 'ADVERT_SUCCESSFUL';
export const ADVERT_FAIL = 'ADVERT_FAIL';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESSFUL = 'USER_SUCCESSFUL';
export const USER_FAIL = 'USER_FAIL';

export const USER_ADVERT_REQUEST = 'USER_ADVERT_REQUEST';
export const USER_ADVERT_SUCCESSFUL = 'USER_ADVERT_SUCCESSFUL';
export const USER_ADVERT_FAIL = 'USER_ADVERT_FAIL';

export const TAGS_REQUEST = 'TAGS_REQUEST';
export const TAGS_SUCCESSFUL = 'TAGS_SUCCESSFUL';
export const TAGS_FAIL = 'TAGS_FAIL';